name: CI 

on:
  push:
    branches:
      - main


jobs:
  job1:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Set up Python
          uses: actions/setup-python@v5
          with:
            python-version: "3.10"

        - name: Install Dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt

        - name: Run Tests with Error Tracing
          run: |
            set -e
            echo "Running tests..."
            pytest --maxfail=3 --disable-warnings -v
