name: CI Pipeline

on:
  push:
    branches:
      - main
      # - any-feature-branch

jobs:
  job1:
    build-and-test:
      runs_on: ubuntu-latest

      steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Set up Python
          uses: actions/setup-python@v5
          with:
            python-version: "3.10"

        - name: Install Dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt

        - name: Run Tests
          run: |
            pytest
